class Weatherbit:
    def __init__(self, weatherbit):    
        self.rh
        self.pod
        self.lon
        self.pres
        self.timezone
        self.ob_time
        self.country_code
        self.clouds
        self.ts
        self.solar_rad
        self.state_code
        self.city_name
        self.wind_spd
        self.wind_cdir_full
        self.wind_cdir
        self.slp
        self.vis
        self.h_angle
        self.sunset
        self.dni
        self.dewpt
        self.snow
        self.uv
        self.precip
        self.wind_dir
        self.sunrise
        self.ghi
        self.dhi
        self.aqi
        self.lat
        self.datetime
        self.temp
        self.station
        self.elev_angle
        self.app_temp